apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: tc-volume-cliam
  labels:
    type: local
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
