all:
  hosts:
    k8snode01:
      ansible_host: 10.91.145.132
      ansible_port: 22
      ansible_user: pirate
      ansible_ssh_private_key_file: ./ssh_keys/id_rsa
    k8snode02:
      ansible_host: 10.91.145.106
      ansible_port: 22
      ansible_user: pirate
      ansible_ssh_private_key_file: ./ssh_keys/id_rsa
    k8snode03:
      ansible_host: 10.91.145.104
      ansible_port: 22
      ansible_user: pirate
      ansible_ssh_private_key_file: ./ssh_keys/id_rsa
    k8snode04:
      ansible_host: 10.91.145.127
      ansible_port: 22
      ansible_user: pirate
      ansible_ssh_private_key_file: ./ssh_keys/id_rsa
    k8snode05:
      ansible_host: 10.91.145.100
      ansible_port: 22
      ansible_user: pirate
      ansible_ssh_private_key_file: ./ssh_keys/id_rsa
  children:
    master:
      k8snode01:
    worker:
      k8snode02:
      k8snode03:
      k8snode04:
      k8snode05:
