---

- hosts: all
  gather_facts: no
  become: yes
  become_user: root
  become_method: sudo

  tasks:
    - name: Shutdown Servers
      shell: sleep 2 && shutdown -h now "Shutdown servers"
      async: 1
      poll: 0
      ignore_errors: true
