---

- hosts: all
  gather_facts: no
  remote_user: pirate
  become: yes
  become_user: root
  become_method: sudo

  tasks:
    - name: Uninstall Kubernetes packages
      apt:
        name:
          - kubelet=1.8.2-00
          - kubeadm=1.8.2-00
          - kubectl=1.8.2-00
          - kubernetes-cni
        state: absent

    - name: Remove Kubernetes configuration
      file:
        path: /etc/kubernetes
        state: absent

    - name: Remove Kubernetes APT Repository
      apt_repository:
        repo: deb http://apt.kubernetes.io/ kubernetes-xenial main
        filename: 'kubernetes'
        state: absent
        update_cache: yes
