---

- hosts: all
  gather_facts: no
  remote_user: pirate
  become: yes
  become_user: root
  become_method: sudo

  tasks:
    - name: Uninstall Kubernetes packages
      apt:
        name:
          - kubelet=1.8.2-00
          - kubeadm=1.8.2-00
          - kubectl=1.8.2-00
        state: absent

    - name: Remove Kubernetes configuration
      file:
        path: "{{ item }}"
        state: absent
      with_items:
        - "/etc/kubernetes"
        - "/etc/cni"
        - "/var/lib/kubelet"
        - "/var/lib/weave"
        - "/var/lib/cni"
        - "/var/lib/etcd"
        - "/var/lib/dockershim"
        - "/opt/cni"

    - name: Remove Kubernetes APT Repository
      apt_repository:
        repo: deb http://apt.kubernetes.io/ kubernetes-xenial main
        filename: 'kubernetes'
        state: absent
        update_cache: yes
